...

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -49,4 +49,4 @@ jobs:
 
       # 5. No CRLF
       - name: Check line endings
-        run: grep -R $'\r' . && { echo "ERROR: CRLF found"; exit 1; } || true
+        run: grep -R $'\r' . && { echo "ERROR. CRLF found"; exit 1; } || true
